name: veep_meep
description: Veep Meep flutter application
version: 0.0.26+15

environment:
  sdk: ">=2.17.3 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  http_mock_adapter: ^0.3.3
  flutter_launcher_icons: ^0.11.0

dependency_overrides:
  flutter_pdfview: 1.2.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/png/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - animations/
    - images/svg/
    - images/png/
    - fonts/
    - assets/sounds/chat-notifications.mp3

  fonts:
    - family: SF-Pro
      fonts:
        - asset: fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Text-Regular.otf
          weight: 400

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  connectivity_plus: ^2.3.9
  permission_handler: ^10.1.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.1.0
  transparent_image: ^2.0.0
  lottie: ^1.4.3
  currency_text_input_formatter: ^2.1.7
  smooth_page_indicator: ^1.0.0+2
  device_info_plus: ^8.1.0
  page_transition: ^2.0.9
  pinput: ^2.2.16
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  swipe_cards: ^1.0.0
  material_segmented_control: ^4.0.0
  device_preview: ^1.1.0
  universal_platform: ^1.0.0+1
  grouped_list: ^5.1.2
  intl: ^0.18.0
  syncfusion_flutter_datepicker: ^20.4.43
  image_cropper: ^3.0.1
  path: ^1.8.0
  reorderable_grid_view: ^2.2.5
  proste_bezier_curve: ^2.0.2
  country_state_city_picker: ^1.2.8
  flutter_screenutil: ^5.6.1
  file_picker: ^5.2.5
  google_sign_in: ^6.1.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter_cached_pdfview: ^0.4.1
  flutter_cache_manager: ^3.3.0
  share_plus: ^7.0.0
  camera: ^0.10.5+2
  icons_plus: ^3.0.0
  gallery_media_picker: ^0.1.0
  photo_view: ^0.14.0
  image_picker: ^0.8.9
  video_player: ^2.6.1
  record: ^4.4.4
  stop_watch_timer: ^2.0.0
  pusher_client: ^2.0.0
  audioplayers: ^4.1.0
  flutter_local_notifications: ^14.1.1




